//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyProduct("EpiCommerceKit.Web")]
[assembly: AssemblyCopyright("Copyright © 2017. All rights reserved.")]
[assembly: AssemblyConfiguration("Debug")]
[assembly: AssemblyVersion("1.0.0")]
[assembly: AssemblyFileVersion("1.0.0")]
[assembly: AssemblyInformationalVersion("0.1.0")]
[assembly: AssemblyTitle("EpiCommerceKit Web, Build Date: 20170410, Git Hash: 570ed33")]
[assembly: AssemblyDescription("Placeholder description.")]
[assembly: AssemblyCompany("WSOL")]
[assembly: ComVisible(false)]


